/**
 * Cloudflare Pages Function: /api/email
 * Sends emails via Resend API with Turnstile + Origin lock + email rate limit.
 *
 * Request body:
 *   type: "report" | "calm_reminder" | "full_report"
 *   email: recipient (validated + blocked-list checked)
 *   turnstileToken: required
 */

import {
  verifyTurnstile, checkEmailRateLimit, isBlockedEmailDomain,
  jsonResponse, corsHeaders, getClientIp, getOrigin, isOriginAllowed
} from './_shared.js';

const ALLOWED_ORIGINS = [
  'https://fengxianpaodao.com',
  'https://www.fengxianpaodao.com',
  'https://skywoo518.github.io',
];

export async function onRequest(context) {
  const { request, env } = context;
  const origin = getOrigin(request);

  // ── 1. CORS preflight ──
  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: corsHeaders(origin, ALLOWED_ORIGINS) });
  }

  // ── 2. Method check ──
  if (request.method !== 'POST') {
    return jsonResponse({ success: false, message: 'Method not allowed' }, 405, origin, ALLOWED_ORIGINS);
  }

  // ── 3. ORIGIN LOCK ──
  const isServerToServer = request.headers.get('X-Verified-Source') === 'risk-runway-internal';
  if (!isServerToServer && !isOriginAllowed(origin, ALLOWED_ORIGINS)) {
    return jsonResponse({ success: false, message: 'Forbidden: origin not allowed.' }, 403, origin, ALLOWED_ORIGINS);
  }

  // ── 4. Parse body ──
  let body;
  try {
    body = await request.json();
  } catch (e) {
    return jsonResponse({ success: false, message: 'Invalid JSON body' }, 400, origin, ALLOWED_ORIGINS);
  }

  const { type, email } = body;

  // ── 5. TURNSTILE VERIFY ──
  if (!isServerToServer) {
    const turnstileToken = body.turnstileToken;
    const turnstileSecret = env.TURNSTILE_SECRET_KEY;
    if (!turnstileSecret) {
      console.error('TURNSTILE_SECRET_KEY env var not set');
      return jsonResponse({ success: false, message: 'Server misconfigured' }, 500, origin, ALLOWED_ORIGINS);
    }
    const ip = getClientIp(request);
    const verify = await verifyTurnstile(turnstileToken, ip, turnstileSecret);
    if (!verify.success) {
      return jsonResponse({ success: false, message: 'Human verification failed. Please refresh and try again.' }, 403, origin, ALLOWED_ORIGINS);
    }
  }

  // ── 6. Validate type & email ──
  if (!type) {
    return jsonResponse({ success: false, message: 'Missing type' }, 400, origin, ALLOWED_ORIGINS);
  }
  if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return jsonResponse({ success: false, message: 'Invalid or missing email' }, 400, origin, ALLOWED_ORIGINS);
  }

  // ── 7. Block disposable email providers ──
  if (isBlockedEmailDomain(email)) {
    return jsonResponse({ success: false, message: 'Disposable email addresses are not allowed. Please use a real email.' }, 400, origin, ALLOWED_ORIGINS);
  }

  // ── 8. EMAIL RATE LIMIT (5/hr, 20/day per IP) ──
  const ip = getClientIp(request);
  const rl = await checkEmailRateLimit(env, ip);
  if (!rl.allowed) {
    return jsonResponse({
      success: false,
      message: rl.reason === 'hourly'
        ? `Too many emails from your network. Limit: 5/hour. Please wait.`
        : `Daily email limit reached (20/day from your network).`
    }, 429, origin, ALLOWED_ORIGINS);
  }

  // ── 9. Get Resend config ──
  const resendKey = env.RESEND_API_KEY;
  const fromAddr = env.RESEND_FROM || 'Risk Runway <notice@fengxianpaodao.com>';
  if (!resendKey) {
    return jsonResponse({ success: false, message: 'Server misconfigured' }, 500, origin, ALLOWED_ORIGINS);
  }

  // ── 10. Build email content ──
  let subject = '';
  let html = '';

  if (type === 'report') {
    subject = 'Your Risk Runway Report';
    const rd = body.reportData || {};
    html = `
      <div style="font-family:Georgia,serif;max-width:600px;margin:0 auto;padding:24px;color:#333">
        <h2 style="color:#1a7a4a;border-bottom:1px solid #d4d1c8;padding-bottom:12px">Your Risk Runway Report</h2>
        <p style="font-size:15px;line-height:1.7">Hi there,</p>
        <p style="font-size:15px;line-height:1.7">Here's your personalized risk runway analysis:</p>
        <div style="background:#f5f4f0;border-radius:8px;padding:16px;margin:16px 0;text-align:center">
          <p style="font-size:13px;color:#888;margin:0 0 4px">Your risk runway</p>
          <p style="font-size:32px;color:#1a7a4a;margin:0;font-weight:700">${rd.runwayDays || '--'} days</p>
        </div>
        <p style="font-size:14px;line-height:1.7;color:#555">${rd.summary || ''}</p>
        <hr style="border:none;border-top:1px solid #d4d1c8;margin:24px 0">
        <p style="font-size:13px;color:#888;line-height:1.6">
          This report was generated by <a href="https://fengxianpaodao.com" style="color:#1a7a4a">Risk Runway</a>.<br>
          Not financial advice. For reference only.
        </p>
      </div>`;
  }

  else if (type === 'full_report') {
    subject = 'Your Risk Runway Report';
    const d = body.data || {};
    const days = d.days || d.runwayDays || '--';
    const summary = d.conclusion || d.summary || '';
    html = `
      <div style="font-family:Georgia,serif;max-width:600px;margin:0 auto;padding:24px;color:#333">
        <h2 style="color:#1a7a4a;border-bottom:1px solid #d4d1c8;padding-bottom:12px">Your Risk Runway Report</h2>
        <div style="background:#f5f4f0;border-radius:8px;padding:20px;margin:16px 0;text-align:center">
          <p style="font-size:13px;color:#888;margin:0 0 6px;text-transform:uppercase;letter-spacing:.1em">Your risk runway</p>
          <p style="font-size:42px;color:#1a7a4a;margin:0;font-weight:700;line-height:1">${days} days</p>
        </div>
        ${summary ? `<p style="font-size:15px;line-height:1.7;background:#fff;padding:16px;border-radius:6px;border:1px solid #d4d1c8">${summary}</p>` : ''}
        ${d.income || d.expenses || d.savings ? `
        <table style="width:100%;border-collapse:collapse;margin:16px 0;font-size:14px">
          ${d.income ? `<tr><td style="padding:8px 0;color:#666">Monthly income</td><td style="padding:8px 0;text-align:right;font-weight:600">$${d.income}</td></tr>` : ''}
          ${d.expenses ? `<tr><td style="padding:8px 0;color:#666">Monthly expenses</td><td style="padding:8px 0;text-align:right;font-weight:600">$${d.expenses}</td></tr>` : ''}
          ${d.savings ? `<tr><td style="padding:8px 0;color:#666">Savings</td><td style="padding:8px 0;text-align:right;font-weight:600">$${d.savings}</td></tr>` : ''}
          ${d.dti ? `<tr><td style="padding:8px 0;color:#666">Debt-to-income</td><td style="padding:8px 0;text-align:right;font-weight:600">${d.dti}%</td></tr>` : ''}
        </table>` : ''}
        <div style="text-align:center;margin:24px 0">
          <a href="https://fengxianpaodao.com/" style="display:inline-block;padding:10px 24px;background:#1a7a4a;color:#fff;text-decoration:none;border-radius:6px;font-size:14px">View full report online →</a>
        </div>
        <hr style="border:none;border-top:1px solid #d4d1c8;margin:24px 0">
        <p style="font-size:13px;color:#888;line-height:1.6">
          This report was generated by <a href="https://fengxianpaodao.com" style="color:#1a7a4a">Risk Runway</a>.<br>
          Not financial advice. For reference only.
        </p>
      </div>`;
  }

  else if (type === 'calm_reminder') {
    subject = '72-Hour Cooling Period Reminder';
    const itemName = body.itemName || 'your purchase';
    const price = body.price || '';
    const runnerId = body.runnerId || '#0000';
    const lang = body.lang || 'en';
    const decisionId = body.decisionId || '';
    const decisionUrl = 'https://fengxianpaodao.com/' + (lang === 'zh' ? 'zh/' : '') +
      'report-deep.html#decision=' + encodeURIComponent(decisionId);

    const t = lang === 'zh' ? {
      hi: 'Hi ' + runnerId + ',',
      body: '72 hours ago you asked me to freeze your decision on <b>' + itemName + '</b> (¥' + price + ').',
      ask: 'Do you still want to buy it? Or has the urge passed?',
      cta: 'Report your decision',
      cta2: 'Continue reflecting on Risk Runway',
      footer: 'This is an automated reminder from Risk Runway.',
    } : {
      hi: 'Hi ' + runnerId + ',',
      body: '72 hours ago you asked me to freeze your decision on <b>' + itemName + '</b> ($' + price + ').',
      ask: 'Do you still want to buy it? Or has the urge passed?',
      cta: 'Report your decision',
      cta2: 'Continue reflecting on Risk Runway',
      footer: 'This is an automated reminder from Risk Runway.',
    };

    html = `
      <div style="font-family:Georgia,serif;max-width:600px;margin:0 auto;padding:24px;color:#333">
        <h2 style="color:#1a7a4a;border-bottom:1px solid #d4d1c8;padding-bottom:12px">72-Hour Cooling Reminder</h2>
        <p style="font-size:15px;line-height:1.7">${t.hi}</p>
        <p style="font-size:15px;line-height:1.7">${t.body}</p>
        <p style="font-size:15px;line-height:1.7">${t.ask}</p>
        <div style="text-align:center;margin:24px 0">
          <a href="${decisionUrl}" style="display:inline-block;padding:10px 24px;background:#1a7a4a;color:#fff;text-decoration:none;border-radius:6px;font-size:14px">${t.cta} →</a>
        </div>
        <p style="text-align:center;margin:8px 0 24px">
          <a href="https://fengxianpaodao.com/${lang === 'zh' ? 'zh/' : ''}report-deep.html" style="color:#888;font-size:13px;text-decoration:underline">${t.cta2}</a>
        </p>
        <hr style="border:none;border-top:1px solid #d4d1c8;margin:24px 0">
        <p style="font-size:13px;color:#888;line-height:1.6">${t.footer}</p>
      </div>`;
  }

  else {
    return jsonResponse({ success: false, message: 'Unknown email type: ' + type }, 400, origin, ALLOWED_ORIGINS);
  }

  // ── 11. Send via Resend ──
  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + resendKey,
      },
      body: JSON.stringify({
        from: fromAddr,
        to: [email],
        subject: subject,
        html: html,
      }),
    });

    const resData = await res.json();
    if (!res.ok) {
      console.error('Resend error:', res.status, JSON.stringify(resData));
      return jsonResponse({ success: false, message: 'Email sending failed. Please try again later.' }, 502, origin, ALLOWED_ORIGINS);
    }

    return jsonResponse({ success: true, message: 'Email sent successfully' }, 200, origin, ALLOWED_ORIGINS);

  } catch (err) {
    console.error('Resend fetch failed:', err);
    return jsonResponse({ success: false, message: 'Network error sending email. Please try again.' }, 502, origin, ALLOWED_ORIGINS);
  }
}
