/**
 * Cloudflare Pages Function: /api/email
 * Sends emails via Resend API.
 *
 * Request body:
 *   type: "report" | "calm_reminder"
 *   email: recipient email
 *   itemName?, price?, runnerId?, lang?, reportData?
 */

export async function onRequest(context) {
  const { request, env } = context;

  // CORS
  if (request.method === 'OPTIONS') {
    return new Response(null, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
      }
    });
  }

  if (request.method !== 'POST') {
    return new Response(JSON.stringify({ success: false, message: 'Method not allowed' }), {
      status: 405,
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
    });
  }

  // Parse body
  let body;
  try {
    body = await request.json();
  } catch (e) {
    return new Response(JSON.stringify({ success: false, message: 'Invalid JSON body' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
    });
  }

  const { type, email } = body;
  if (!type || !email) {
    return new Response(JSON.stringify({ success: false, message: 'Missing type or email' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
    });
  }

  // Validate email format
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return new Response(JSON.stringify({ success: false, message: 'Invalid email format' }), {
      status: 400,
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
    });
  }

  // Get env vars
  const resendKey = env.RESEND_API_KEY;
  const fromAddr = env.RESEND_FROM || 'Risk Runway <notice@fengxianpaodao.com>';

  if (!resendKey) {
    return new Response(JSON.stringify({ success: false, message: 'Server misconfigured: missing Resend API key' }), {
      status: 500,
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
    });
  }

  // Build email content based on type
  let subject = '';
  let html = '';

  if (type === 'report') {
    subject = 'Your Risk Runway Report';
    const rd = body.reportData || {};
    html = `
      <div style="font-family:Georgia,serif;max-width:600px;margin:0 auto;padding:24px;color:#333">
        <h2 style="color:#1a7a4a;border-bottom:1px solid #d4d1c8;padding-bottom:12px">Your Risk Runway Report</h2>
        <p style="font-size:15px;line-height:1.7">Hi there,</p>
        <p style="font-size:15px;line-height:1.7">Here's your personalized risk runway analysis:</p>
        <div style="background:#f5f4f0;border-radius:8px;padding:16px;margin:16px 0;text-align:center">
          <p style="font-size:13px;color:#888;margin:0 0 4px">Your risk runway</p>
          <p style="font-size:32px;color:#1a7a4a;margin:0;font-weight:700">${rd.runwayDays || '--'} days</p>
        </div>
        <p style="font-size:14px;line-height:1.7;color:#555">${rd.summary || ''}</p>
        <hr style="border:none;border-top:1px solid #d4d1c8;margin:24px 0">
        <p style="font-size:13px;color:#888;line-height:1.6">
          This report was generated by <a href="https://fengxianpaodao.com" style="color:#1a7a4a">Risk Runway</a>.<br>
          Not financial advice. For reference only.
        </p>
      </div>`;
  }

  else if (type === 'calm_reminder') {
    subject = '72-Hour Cooling Period Reminder';
    const itemName = body.itemName || 'your purchase';
    const price = body.price || '';
    const runnerId = body.runnerId || '#0000';
    const lang = body.lang || 'en';

    const t = lang === 'zh' ? {
      hi: 'Hi ' + runnerId + ',',
      body: '72 hours ago you asked me to freeze your decision on <b>' + itemName + '</b> (¥' + price + ').',
      ask: 'Do you still want to buy it? Or has the urge passed?',
      cta: 'Continue reflecting on Risk Runway',
      footer: 'This is an automated reminder from Risk Runway.',
    } : {
      hi: 'Hi ' + runnerId + ',',
      body: '72 hours ago you asked me to freeze your decision on <b>' + itemName + '</b> ($' + price + ').',
      ask: 'Do you still want to buy it? Or has the urge passed?',
      cta: 'Continue reflecting on Risk Runway',
      footer: 'This is an automated reminder from Risk Runway.',
    };

    html = `
      <div style="font-family:Georgia,serif;max-width:600px;margin:0 auto;padding:24px;color:#333">
        <h2 style="color:#1a7a4a;border-bottom:1px solid #d4d1c8;padding-bottom:12px">72-Hour Cooling Reminder</h2>
        <p style="font-size:15px;line-height:1.7">${t.hi}</p>
        <p style="font-size:15px;line-height:1.7">${t.body}</p>
        <p style="font-size:15px;line-height:1.7">${t.ask}</p>
        <div style="text-align:center;margin:24px 0">
          <a href="https://fengxianpaodao.com/report-deep.html" style="display:inline-block;padding:10px 24px;background:#1a7a4a;color:#fff;text-decoration:none;border-radius:6px;font-size:14px">${t.cta} →</a>
        </div>
        <hr style="border:none;border-top:1px solid #d4d1c8;margin:24px 0">
        <p style="font-size:13px;color:#888;line-height:1.6">${t.footer}</p>
      </div>`;
  }

  else {
    return new Response(JSON.stringify({ success: false, message: 'Unknown email type: ' + type }), {
      status: 400,
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
    });
  }

  // Send via Resend
  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + resendKey,
      },
      body: JSON.stringify({
        from: fromAddr,
        to: [email],
        subject: subject,
        html: html,
      }),
    });

    const resData = await res.json();

    if (!res.ok) {
      console.error('Resend error:', res.status, JSON.stringify(resData));
      return new Response(JSON.stringify({
        success: false,
        message: 'Email sending failed. Please try again later.'
      }), {
        status: 502,
        headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
      });
    }

    return new Response(JSON.stringify({ success: true, message: 'Email sent successfully' }), {
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
    });

  } catch (err) {
    console.error('Resend fetch failed:', err);
    return new Response(JSON.stringify({
      success: false,
      message: 'Network error sending email. Please try again.'
    }), {
      status: 502,
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' }
    });
  }
}
